############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Panel"
url = "/service/panel"
weight = 1

[[main]]
name = "Seamless PBX"
url = "/service/seamless_pbx"
weight = 1

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
