openapi: 3.0.0

info:
  title: Seamless VOIP
  description: Cloud-base PBX
  version: 0.1.0

servers:
  - url: http://api.voipstack.io/v1
    description: Main (production) server
  - url: http://staging-api.voipstack.io/v1
    description: Internal staging server for testing

paths:
  /provider/v1/state/:
    post:
      summary: Returns a state of pbx
      description: .
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
  /provider/v1/action/:
    post:
      summary: Returns a state of pbx
      description: .
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
  /provider/v1/callback/:
    post:
      summary: Returns a state of pbx
      description: .
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
